# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# tag for pytorch-operator image
tag: v1.1.0

# tag for di-orchestrator image
registry: opendilab
serviceDomainName: svc.cluster.local

operatorName: di-operator
serverName: di-server
serverPort: 8081

qps: 100

burst: 200
